// <auto-generated/>
using _6_AdditionalFunction;
using _6_AdditionalFunction.Nodes;
using StateMachine;

namespace StateMachineDemoShared.Pages
{
    public partial class Home
    {

        private ProcedureView pv = default!;
        private FSMExecutor? executor;

        protected override Task OnInitializedAsync()
        {
            return base.OnInitializedAsync();
        }

        private async Task InitAExample()
        {
            await this.pv.ImportFromScript(EasyScript.ScriptText);
        }

        protected override Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                pv.Engine.GroupNodeStateChanged += Executor_NodeStateChanged;
                pv.Engine.GroupNodeExitChanged += Executor_NodeExitChanged;
            }
            return base.OnAfterRenderAsync(firstRender);
        }

        private void CreateExecutor()
        {
            if (executor is not null)
            {
                executor.FSMStateChanged -= Executor_FSMStateChanged;
                executor.NodeStateChanged -= Executor_NodeStateChanged;
                executor.NodeExitChanged -= Executor_NodeExitChanged;
            }
            if (pv.Engine.TryGetNode("Start", out IFSMNode StateState))
            {
                if (!pv.Engine.TryGetEvent("EndEvent", out FSMEvent end))
                {
                    end = new FSMEvent("EndEvent");
                }
                executor = new FSMExecutor(StateState, end);
                executor.FSMStateChanged += Executor_FSMStateChanged;
                executor.NodeStateChanged += Executor_NodeStateChanged;
                executor.NodeExitChanged += Executor_NodeExitChanged;
            }
        }

        private async void Executor_NodeExitChanged(object sender, string e)
        {
            if (pv is null)
                return;
            await pv.SetInactive(e);
            //nodeState.Add((e, false));
        }

        private async void Executor_NodeStateChanged(object sender, string e)
        {
            if (pv is null)
                return;
            await pv.SetActive(e);
            //nodeState.Add((e, true));
        }

        private void Executor_FSMStateChanged(FSMExecutor arg1, FSMState newState, FSMState oldState)
        {
            switch (newState)
            {
                case FSMState.Uninitialized:
                    break;
                case FSMState.Initialized:
                    canStart = true;
                    canPause = false;
                    canContinue = false;
                    break;
                case FSMState.Proceeding:
                case FSMState.Running:
                    canStart = false;
                    canPause = true;
                    canContinue = false;
                    break;
                case FSMState.Pausing:
                    canStart = false;
                    canPause = false;
                    canContinue = false;
                    break;
                case FSMState.Paused:
                    canStart = false;
                    canPause = false;
                    canContinue = true;
                    break;
                case FSMState.Stopping:
                    canStart = false;
                    canPause = false;
                    canContinue = false;
                    break;
                case FSMState.Finished:
                    canStart = true;
                    canPause = false;
                    canContinue = false;
                    break;
                case FSMState.Stoped:
                    canStart = true;
                    canPause = false;
                    canContinue = false;
                    break;
                default:
                    canStart = false;
                    canPause = false;
                    canContinue = false;
                    break;
            }
            InvokeAsync(StateHasChanged);
        }
        private bool canStart = true;
        public async Task Start()
        {
            CreateExecutor();
            if (executor is not null)
            {
                await executor.RestartAsync(new MyContext(), true);
            }
        }

        private bool canPause = false;
        public async Task Pause()
        {
            if (executor is not null)
            {
                await executor.PauseAsync();
            }
        }

        private bool canContinue = false;
        public void Continue()
        {
            if (executor is not null)
            {
                executor.Continue();
            }
        }

        public async Task Stop()
        {
            if (executor is not null)
            {
                await executor.StopAsync();
            }
        }
    }
}